language: python

sudo: required

services:
  - docker

before_install:
  - git clone --recurse-submodules git://github.com/sbesson/omero-test-infra -b cli_pycheck .omero

script:
  - .omero/docker scripts
