---
name: OMERO
on:
  push:
  pull_request:

jobs:
  test:
    name: Run integration tests against OMERO
    runs-on: ubuntu-latest
    env:
      STAGE: scripts
    steps:
      - uses: actions/checkout@v2
      - name: Checkout omero-test-infra
        uses: actions/checkout@master
        with:
          repository: ome/omero-test-infra
          path: .omero
          ref: ${{ secrets.OMERO_TEST_INFRA_REF }}
      - name: Build and run OMERO tests
        run: .omero/docker $STAGE
